/**
 * Auto-generated environment configuration.
 * Generated by inject-env.js at 2026-08-28T16:36:38.430Z
 * DO NOT EDIT DIRECTLY. Edit .env.local or Netlify environment variables instead.
 */
(function() {
  'use strict';
  window.__OMSHARE_ENV__ = {
  "FIREBASE_API_KEY": "AIzaSyACPvi35S8zIpcPpRR1vM00lvnBw1KT9n8",
  "FIREBASE_AUTH_DOMAIN": "om-share-af20d.firebaseapp.com",
  "FIREBASE_PROJECT_ID": "om-share-af20d",
  "FIREBASE_STORAGE_BUCKET": "om-share-af20d.firebasestorage.app",
  "FIREBASE_MESSAGING_SENDER_ID": "317126961668",
  "FIREBASE_APP_ID": "1:317126961668:web:87767a6cb54d979bb62351",
  "FIREBASE_MEASUREMENT_ID": "G-YXL3ZSMHSP",
  "STUN_SERVERS": "stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302,stun:stun2.l.google.com:19302",
  "CODE_EXPIRY": "86400000",
  "CHUNK_SIZE": "65536"
};
  
  // Backwards-compatibility globals
  window.FIREBASE_API_KEY = "AIzaSyACPvi35S8zIpcPpRR1vM00lvnBw1KT9n8";
  window.FIREBASE_AUTH_DOMAIN = "om-share-af20d.firebaseapp.com";
  window.FIREBASE_PROJECT_ID = "om-share-af20d";
  window.FIREBASE_STORAGE_BUCKET = "om-share-af20d.firebasestorage.app";
  window.FIREBASE_MESSAGING_SENDER_ID = "317126961668";
  window.FIREBASE_APP_ID = "1:317126961668:web:87767a6cb54d979bb62351";
  window.FIREBASE_MEASUREMENT_ID = "G-YXL3ZSMHSP";
  window.STUN_SERVERS = "stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302,stun:stun2.l.google.com:19302";
  window.CODE_EXPIRY = "86400000";
  window.CHUNK_SIZE = "65536";
})();
