/**
 * Build script to generate js/env-config.js from environment variables
 * Supports .env.local, .env, .env.production, and process.env
 * Run: node inject-env.js
 */

const fs = require('fs');
const path = require('path');

// Try loading dotenv files if available
try {
  const dotenv = require('dotenv');
  // Load in priority order: .env.local -> .env
  if (fs.existsSync(path.join(__dirname, '.env.local'))) {
    dotenv.config({ path: path.join(__dirname, '.env.local') });
  }
  if (fs.existsSync(path.join(__dirname, '.env'))) {
    dotenv.config({ path: path.join(__dirname, '.env') });
  }
} catch (e) {
  // dotenv not found, fallback to process.env
}

function getEnv(key, viteKey) {
  return process.env[key] || (viteKey ? process.env[viteKey] : undefined) || '';
}

const envConfig = {
  FIREBASE_API_KEY: getEnv('FIREBASE_API_KEY', 'VITE_FIREBASE_API_KEY'),
  FIREBASE_AUTH_DOMAIN: getEnv('FIREBASE_AUTH_DOMAIN', 'VITE_FIREBASE_AUTH_DOMAIN'),
  FIREBASE_PROJECT_ID: getEnv('FIREBASE_PROJECT_ID', 'VITE_FIREBASE_PROJECT_ID'),
  FIREBASE_STORAGE_BUCKET: getEnv('FIREBASE_STORAGE_BUCKET', 'VITE_FIREBASE_STORAGE_BUCKET'),
  FIREBASE_MESSAGING_SENDER_ID: getEnv('FIREBASE_MESSAGING_SENDER_ID', 'VITE_FIREBASE_MESSAGING_SENDER_ID'),
  FIREBASE_APP_ID: getEnv('FIREBASE_APP_ID', 'VITE_FIREBASE_APP_ID'),
  FIREBASE_MEASUREMENT_ID: getEnv('FIREBASE_MEASUREMENT_ID', 'VITE_FIREBASE_MEASUREMENT_ID'),
  STUN_SERVERS: getEnv('STUN_SERVERS', 'VITE_STUN_SERVERS'),
  TURN_SERVERS: getEnv('TURN_SERVERS', 'VITE_TURN_SERVERS'),
  SIGNALING_SERVER_URL: getEnv('SIGNALING_SERVER_URL', 'VITE_SIGNALING_SERVER_URL'),
  CODE_EXPIRY: getEnv('CODE_EXPIRY', 'VITE_CODE_EXPIRY'),
  MAX_FILE_SIZE: getEnv('MAX_FILE_SIZE', 'VITE_MAX_FILE_SIZE'),
  CHUNK_SIZE: getEnv('CHUNK_SIZE', 'VITE_CHUNK_SIZE')
};

// Filter out keys that have empty values
const activeConfig = {};
for (const [k, v] of Object.entries(envConfig)) {
  if (v && v.trim() !== '') {
    activeConfig[k] = v.trim();
  }
}

// Ensure js directory exists
const jsDir = path.join(__dirname, 'js');
if (!fs.existsSync(jsDir)) {
  fs.mkdirSync(jsDir, { recursive: true });
}

// Generate js/env-config.js
const envConfigFileContent = `/**
 * Auto-generated environment configuration.
 * Generated by inject-env.js at ${new Date().toISOString()}
 * DO NOT EDIT DIRECTLY. Edit .env.local or Netlify environment variables instead.
 */
(function() {
  'use strict';
  window.__OMSHARE_ENV__ = ${JSON.stringify(activeConfig, null, 2)};
  
  // Backwards-compatibility globals
  ${Object.entries(activeConfig).map(([k, v]) => `window.${k} = ${JSON.stringify(v)};`).join('\n  ')}
})();
`;

fs.writeFileSync(path.join(jsDir, 'env-config.js'), envConfigFileContent);

console.log('✓ Environment variables successfully generated in js/env-config.js');
console.log('  Active variables:', Object.keys(activeConfig).join(', ') || '(none - using default fallbacks)');